#pragma once

#include "../State/Reader.hpp"

#include <queue>
#include <vector>

// Very hacky way of signalling to Windows this is generated by the AI
#define WM_FTLAI 0x800

enum class MouseButton
{
	Left, Middle, Right
};

constexpr Duration ZERO_DURATION = Duration(0);

class Input
{
public:
	static constexpr int GAME_WIDTH = 1280;
	static constexpr int GAME_HEIGHT = 720;

	Input() = delete;

	static void iterate(); // make inputs
	static bool inputs(); // check if any inputs are queued
	static bool ready(); // check if ready
	static void setReady(bool ready = true); // sets the ready state
	static void allowHumanMouse(bool allow = true); // sets if human mouse input is allowed
	static void allowHumanKeyboard(bool allow = true); // sets if human keyboard input is allowed
	static bool humanMouseAllowed(); // checks if human mouse input is allowed
	static bool humanKeyboardAllowed(); // checks if human keyboard input is allowed

	// All inputs below are added to a queue, not done immediately
	// This is so they're roughly executed sequentially

	static void mouseMove(
		const Point<int>& pos,
		Duration delay = ZERO_DURATION
	);

	static void mouseMove(
		int x, int y,
		Duration delay = ZERO_DURATION
	);

	static void mouseDown(
		const Point<int>& pos,
		MouseButton button = MouseButton::Left,
		bool shift = false,
		bool ctrl = false,
		Duration delay = ZERO_DURATION
	);

	static void mouseDown(
		int x, int y,
		MouseButton button = MouseButton::Left,
		bool shift = false,
		bool ctrl = false,
		Duration delay = ZERO_DURATION
	);

	static void mouseUp(
		const Point<int>& pos,
		MouseButton button = MouseButton::Left,
		bool shift = false,
		bool ctrl = false,
		Duration delay = ZERO_DURATION
	);

	static void mouseUp(
		int x, int y,
		MouseButton button = MouseButton::Left,
		bool shift = false,
		bool ctrl = false,
		Duration delay = ZERO_DURATION
	);

	static void mouseClick(
		const Point<int>& pos,
		MouseButton button = MouseButton::Left,
		bool shift = false,
		bool ctrl = false,
		Duration delay = ZERO_DURATION
	);

	static void mouseClick(
		int x, int y,
		MouseButton button = MouseButton::Left,
		bool shift = false,
		bool ctrl = false,
		Duration delay = ZERO_DURATION
	);

private:
	class Impl;
	static Impl impl;

	static bool good, humanMouse, humanKeyboard;
};
